version: "3.8"

services:
  app:
    build: .
    restart: on-failure
    depends_on:
      - database
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      WAIT_HOSTS: database:3306
      MYSQL_DSN: root:dbpass@tcp(database:3306)/url-shortener?charset=utf8mb4&parseTime=True&loc=Local

  database:
    image: mysql:8.2.0

    environment:
      - MYSQL_ROOT_PASSWORD=dbpass
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=url-shortener
    ports:
      - "3306:3306"